### ISSUE TITLE
Martial Arts broken when TCoE added to sheet

### ISSUE THREAD

**Issue by praxidicae** [Metacomet10/MPMB-v13-content-catchup#15]
For some reason, when TCoE is added (not even activated, just imported into the sheet and then moved to the "Excluded from the Automation" column in the resources window), Monk loses it's martial arts ability in the attacks section of the sheet (i.e. Unarmed Strike defaults to Str based and does 1+Str damage).

If you already have a lvl 1+ monk with the martial arts active it still seems to work if you subsequently add TCoE, activate it and then level up.

However, if you add TCoE (and even if you immediately move it to the excluded column) and start a new character (or Reset the sheet to start anew) it forgets that you can use Dex and that damage scales from 1d4+.

**Comment by Metacomet10** [comment]
Repository deprecated. Closing all issues.
