### ISSUE TITLE
Ranger Deft Explorer feature creates error with '2020/10/27 - all_WotC_pub+UA.min.js'

### ISSUE THREAD

**Issue by Uncurlhalo** [Metacomet10/MPMB-v13-content-catchup#16]
**Describe the bug**
When attempting to create a Fey Wanderer Ranger the following error gets thrown after saving and re-opening a sheet that has the TCoE content added where a Fey Wanderer character has been selected via the Class menu.
`The script '2020/10/27 - all_WotC_pub+UA.min.js' is faulty, it returns the following error when run:
"TypeError: origNatExpl[origNatExplCurSel] is undefined"
The script ahs been removed from this pdf.`

**To Reproduce**
1. Open a fresh copy of the base MPMB character sheet.
2. Add TCoE js file from this repo.
3. Create a character with the Fey Wanderer class
4. Save the file and close it.
5. Open the file.
6. The error appears and the related JS file is removed.

**Expected behavior**
No error pop-up should occur and the base JS files included with a fresh sheet should not be removed.

**Screenshots**
![JavascirptError](https://user-images.githubusercontent.com/2711960/108275602-92d3c900-7144-11eb-9efa-395f3843dec9.PNG)
![ClassesUsed](https://user-images.githubusercontent.com/2711960/108275778-d595a100-7144-11eb-87fe-4ad5a92f50df.PNG)

**Version of the sheet:**
 - v13.0.5 

**Additional context**
The included classes selection shows other classes and higher than 1 level in the class but it will happen with just a single level in Fey Wanderer.

**Comment by Metacomet10** [comment]
Confirmed happening with all Ranger subclasses when Tasha's script is imported. Pushed commit https://github.com/Metacomet10/MPMB-v13-content-catchup/commit/2ed6cb1e93431c729e8d3ad018d9ad01273b6bad as a temporary fix

**Comment by Metacomet10** [comment]
This only happens when TCoE and UA:CFV are imported into the same sheet.

**Comment by Metacomet10** [comment]
Repository deprecated. Closing all issues.
