### ISSUE TITLE
UA Spells & Magic Tattoos Rarity Bug

### ISSUE THREAD

**Issue by gentlemonmatt** [Metacomet10/MPMB-v13-content-catchup#20]
Bug details:
With the script for the UA: Spells & Magic Tattoos, there is a coding error with the Barrier Tattoo regarding its rarity options and AC provision. No "Uncommon" option is available, and the three options provided all only allow the AC to be 18 instead of the varied options. From examination of script within GitHub, it seems the script may be missing code or may have incorrect code.

Reproduction for Evidence:
1. Have script ua_20200326_Spells-and-Magic-Tattoos added into sheet. (Testing done on Printer-Friendly version as no selection tabs available in Colorful sheet.)
2. Scroll to "Magic Items" section and select item to be "Barrier Tattoo" of either of three options. (Can be found in source > UA: Spells & Magic Tattoos.)
3. Scroll to first page and change description on Armor box to "Barrier Tattoo". AC then becomes 18.

Expected Behaviour:
When option is selected for Barrier Tattoo, the description should be correct to the rarity selected.
When selected, the Rarity should also be within the Magic Item name box with name of Tattoo.
When Uncommon/Rare/Very Rare is selected for specific tattoo, the AC should in fact match the correct information when chosen in the description box of Armor.

Screenshots:
Screen of Magic Item description:
![image](https://user-images.githubusercontent.com/80161778/110209578-0d3c7100-7ed9-11eb-9f36-0b9d4c3bcbe5.png)
Screen of supposed "Rarity" selections in option box:
![image](https://user-images.githubusercontent.com/80161778/110209639-3eb53c80-7ed9-11eb-832b-4f5e7be3d7e6.png)
Screen of Armor description box and applied AC value:
![image](https://user-images.githubusercontent.com/80161778/110209665-5ab8de00-7ed9-11eb-9d65-9666d89fcd4f.png)
Screen of possible error in script code design leading to bug in question:
![image](https://user-images.githubusercontent.com/80161778/110209691-7ae89d00-7ed9-11eb-9d77-4494ebe50f16.png)

Version of sheet used:
v13.0.4 Printer-Friendly - Redesign

**Comment by Metacomet10** [comment]
Very simple fix. I'm not sure how it's suddenly been almost 3 *months* but, uhhhh, better late than never I guess? Sorry! 😓
Fixed in this commit: https://github.com/Metacomet10/MPMB-v13-content-catchup/commit/8821b7d3c5745369001ea167fd4ac42984b1ec33
